spring.application.name=projeto

spring.datasource.driver-class-name=org.postgresql.Driver

#external HOST
#jdbc:postgresql://dpg-d0b7sap5pdvs73ceoc70-a.oregon-postgres.render.com/organizacao
spring.datasource.url=//dpg-d0b7sap5pdvs73ceoc70-a/organizacao
spring.datasource.username=organizacao_user
spring.datasource.password=f7Gw1B1Ft9JJXUX5muUhpcwHEs56klwJ

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true